#############################################################################
# Makefile for building: libmpv.a
# Generated by qmake (3.1) (Qt 5.13.0)
# Project:  mpv.pro
# Template: lib
# Command: /Users/s1ngular/GoWork/src/github.com/therecipe/env_darwin_amd64_513/5.13.0/clang_64/bin/qmake -o Makefile mpv.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -fPIC $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -fPIC -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W $(DEFINES)
INCPATH       = -I. -I/usr/local/Cellar/mpv/0.32.0_5/include -I../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtQuick.framework/Headers -I../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtGui.framework/Headers -I../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtQml.framework/Headers -I../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtNetwork.framework/Headers -I../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/macx-clang -F/Users/s1ngular/GoWork/src/github.com/therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib
QMAKE         = /Users/s1ngular/GoWork/src/github.com/therecipe/env_darwin_amd64_513/5.13.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/s1ngular/GoWork/src/github.com/therecipe/env_darwin_amd64_513/5.13.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/s1ngular/GoWork/src/github.com/therecipe/env_darwin_amd64_513/5.13.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mpv1.0.0
DISTDIR = /Users/s1ngular/GoWork/src/github.com/organicio/mpv/.tmp/mpv1.0.0
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = mpv.cpp moc_mpv.cpp
OBJECTS       = mpv.o \
		moc_mpv.o
DIST          = ../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/spec_pre.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/qdevice.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/device_config.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/unix.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/mac.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/macx.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/sanitize.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/gcc-base.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/clang.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/clang-mac.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/qconfig.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/qt_functions.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/qt_config.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/spec_post.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/toolchain.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/default_pre.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/resolve_config.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/default_post.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/link_pkgconfig.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/mac.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/warn_on.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/qt.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/resources.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/moc.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/unix/thread.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/qmake_use.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/file_copies.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/rez.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/exceptions.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/yacc.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/lex.prf \
		mpv.pro mpv.h mpv.cpp
QMAKE_TARGET  = mpv
DESTDIR       = 
TARGET        = libmpv.a

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/s1ngular/GoWork/src/github.com/organicio/mpv/mpv.pro


first: all
####### Build rules

staticlib: $(TARGET)

libmpv.a:  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGET)
	$(AR) $(DESTDIR)$(TARGET) $(OBJECTS)
	$(RANLIB) $(TARGET)


Makefile: mpv.pro ../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf ../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/spec_pre.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/qdevice.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/device_config.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/unix.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/mac.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/macx.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/sanitize.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/gcc-base.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/clang.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/clang-mac.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/qconfig.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/qt_functions.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/qt_config.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/spec_post.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/toolchain.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/default_pre.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/resolve_config.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/default_post.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/link_pkgconfig.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/mac.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/warn_on.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/qt.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/resources.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/moc.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/unix/thread.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/qmake_use.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/file_copies.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/rez.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/exceptions.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/yacc.prf \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/lex.prf \
		mpv.pro
	$(QMAKE) -o Makefile mpv.pro
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/spec_pre.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/qdevice.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/device_config.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/unix.conf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/mac.conf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/macx.conf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/sanitize.conf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/gcc-base.conf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/clang.conf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/common/clang-mac.conf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/qconfig.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_script.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/qt_functions.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/qt_config.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/spec_post.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/sdk.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/toolchain.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/default_pre.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/resolve_config.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/default_post.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/default_post.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/link_pkgconfig.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/mac.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/warn_on.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/qt.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/resources.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/moc.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/unix/opengl.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/unix/thread.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/qmake_use.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/file_copies.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/rez.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/testcase_targets.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/exceptions.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/yacc.prf:
../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/lex.prf:
mpv.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile mpv.pro

qmake_all: FORCE


all: Makefile libmpv.a

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mpv.h $(DISTDIR)/
	$(COPY_FILE) --parents mpv.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -fPIC -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h ../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mpv.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mpv.cpp
moc_mpv.cpp: mpv.h \
		/usr/local/Cellar/mpv/0.32.0_5/include/mpv/client.h \
		/usr/local/Cellar/mpv/0.32.0_5/include/mpv/render_gl.h \
		/usr/local/Cellar/mpv/0.32.0_5/include/mpv/render.h \
		qthelper.hpp \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/QString \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtGui.framework/Headers/QList \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/QHash \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/qhash.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/QMetaType \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		moc_predefs.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/bin/moc
	/Users/s1ngular/GoWork/src/github.com/therecipe/env_darwin_amd64_513/5.13.0/clang_64/bin/moc $(DEFINES) --include /Users/s1ngular/GoWork/src/github.com/organicio/mpv/moc_predefs.h -I/Users/s1ngular/GoWork/src/github.com/therecipe/env_darwin_amd64_513/5.13.0/clang_64/mkspecs/macx-clang -I/Users/s1ngular/GoWork/src/github.com/organicio/mpv -I/usr/local/Cellar/mpv/0.32.0_5/include -I/Users/s1ngular/GoWork/src/github.com/therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtQuick.framework/Headers -I/Users/s1ngular/GoWork/src/github.com/therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtGui.framework/Headers -I/Users/s1ngular/GoWork/src/github.com/therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtQml.framework/Headers -I/Users/s1ngular/GoWork/src/github.com/therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtNetwork.framework/Headers -I/Users/s1ngular/GoWork/src/github.com/therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/s1ngular/GoWork/src/github.com/therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib mpv.h -o moc_mpv.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

mpv.o: mpv.cpp mpv.h \
		/usr/local/Cellar/mpv/0.32.0_5/include/mpv/client.h \
		/usr/local/Cellar/mpv/0.32.0_5/include/mpv/render_gl.h \
		/usr/local/Cellar/mpv/0.32.0_5/include/mpv/render.h \
		qthelper.hpp \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/QString \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtGui.framework/Headers/QList \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/QHash \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/qhash.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/QMetaType \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/QObject \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/QtGlobal \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../therecipe/env_darwin_amd64_513/5.13.0/clang_64/lib/QtGui.framework/Headers/qguiapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpv.o mpv.cpp

moc_mpv.o: moc_mpv.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mpv.o moc_mpv.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

